name: RunJobs
on:
  push:
jobs:
  validateHtml:
    runs-on: windows-latest

    steps:
      - name: get-code
        uses: actions/checkout@v5

      - name: html file exit
        run: test -f Pratice/index.html

  validateJs:
    runs-on: windows-latest

    steps:
      - name: get-code
        uses: actions/checkout@v5

      - name: script file exit
        run: test -f Pratice/script.js

  validateCode:
    needs: [validateHtml, validateJs]
    runs-on: windows-latest

    steps:
      - name: get-code
        uses: actions/checkout@v5

      - name: valid html file
        run: npx htmlhint "**/*.html"

      - name: valid js file
        run: node --check Pratice/script.js
