name: Second-WF
on:
  push:
  workflow_dispatch:
jobs:
  hello-job:
    runs-on: windows-latest
    steps:
      - name: "Welcome"
        run: echo "welcome run"

  middle-job:
    runs-on: windows-latest
    steps:
      - name: "middle"
        run: echo "middle run"

  by-job:
    runs-on: windows-latest
    steps:
      - name: "by"
        run: echo "buy run"
